"use strict";

module.exports = {
  SUCCESS_CODE: 200,
  ALLREADY_EXIST: 201,
  ERROR_CODE: 400,
  AUTH_CODE: 401,
  TOKEN_CODE: 417,
  SESSION_EXPIRED: "Your session is expired. Please login again to continue",
  TOKEN_ERROR: "Login token is Required",
  PROFILEIMAGE: "../backend/app/uploads/profileImages/",
  INCORRECT_FILE_TYPE:
    "Incorrect file type! Accepted file types are : jpg, jpeg, png, gif",
  INVALID_JSON: "Content Not Found",
  INTERNAL_ERROR_CODE: 500,
  FAILURE: "failure",
  ERROR: "Error",

  //LOGIN LOGS
  ACCESS: "Accessed",
  ROLE_MSG: "Wrong role selected",
  EMAIL_EXIST_ALREADY: "Email Already Exist",
  ACCOUNT_CREATED: "Account create successfully.",
  ROLE_MESSAGE: "Please enter the correct role.",
  DEFAULT_PASSWORD: "123456",
  INVALID_TOKEN: "Token expired. Please login again",
  TOKEN_ERROR: "Login token is Required",
  LOGIN_SUCESS: "Logged In Successfully",
  INVALID_LOGIN: "Username or Password is not valid",
  ADDED_SUCCESS: "saved successfully",
  UPDATE_SUCCESS: "Updated Successfully",
  LOGGED_OUT: "User Logout Successfully",
  INVALID_EMAIL: "Email Not VALID",
  EMAIL_NOTIFICATION_SEND: "Email and SMS are sent successfully",
  DELETE_SUCCESS: "Deleted Successfully",
  FETCH_SUCCESS: "Fetched Successfully",
  SENT_SUCCESS: "Sent Successfully",
  CODE_EXPIRES: "Registeration Code Expires",
  FAILED_TO_PROCESS: "Failed to Process",
  NO_PROGRAM_ASSIGN: "No program assigned",
  SAME_SLEEP_SAVED_DAY: "Same Sleep Time Already saved for today",
  REQUIRED_FIELDS_MISSING: "Required Fields Missing",
  USER_ALREADY_EXIST: "User Already Exist. Please try with another user",
  PHONE_ALREADY_EXIST:
    "Phone number Already Exist. Please try with another number",
  CAT_ALREADY_EXIST: "Category Already Exist. Please try with another category",
  USER_DOEST_NOT_EXIST: "User Does not exist. Please register",
  INTERNAL_ERROR: "Internal Error",
  PROCESS_CALL: "You can start the call",
  NOT_A_TIME_TO_CALL:
    "You can only start call before 10 minutes of appointment",
  NOTIFICATION_SEND: "Notification Sent",
  INVALID_USER_TOKEN: "Invalid User Registration Link",
  NO_DATA_FOUND: "No data found",
  PAST_PATIENT_POINTS: "Fetched Successfully Past Patient Points",
  PAST_PATIENT_SLEEP_TRACKER_POINTS: "Fetched Past Sleep Tracker Successfully",
  PAST_PATIENT_ACTIVITY_TRACKER: "Fetched Past Activity Tracker Successfully",
  PAST_PATIENT_MOOD_TRACKER: "Fetched Past Mood Tracker Successfully",
  PAST_PATIENT_TRACKER_DATA: "Fetched Past Patient Tracker Data Successfully",
  DAILY_INFO_USEFUL:
    "Thank you for your feedback. We're glad you found this information useful. Please tell us what you liked about this content in the comments section below.",
  DAILY_INFO_NOT_USEFUL:
    "Thank you for your feedback. We're sorry you didn't find this information useful. Please tell us how we can improve this content in the comments section below.",
  ACCOUNT_TEMPORY_LOCK:
    "Your account is temporary locked. Please contact admin.",
  RESPONSE_RECORDED: "Thank you. Your response has been recorded.",
  SAVE_ACTIVITY: "Your activities have been saved",
  UPDATE_ACTIVITY: "Your activities have been saved",
  SAVE_SLEEP_TRACKER: "Your sleep has been saved",
  UPDATE_SLEEP_TRACKER: "Your sleep has been updated",
  KEY_WORD: "Keyword Already Exist. Please try with another keyword",
  NO_RECORDS_FOUND: "No Records in the database",
  INCORRECT_PASSWORD: "Incorrect Password",
  PHYSICIANS_FETCHED: "Physician Fethced Successfully",
  DATA_FAILED: "Data Failed",
  NURSE_FETCHED: "Nurse Fetched Successfully",
  NURSE_UPDATED: "Nurse update successfully",
  ASSISSTED_LIVE_FETCHED: "Assisted Livings Fetched Successfully",
  GEO_LOCATION_UPDATED: "Geo Location Updated Successfully",
  FETCH_NURSE_PHYSICIAN: "Nurses & Physician Fetched Successfully.",
  UPDATE_ASSISTED_LIVE: "Assisted Living update successfully.",
  OTHER_FETCHED: "Others Fetched Successfully.",
  NOT_FOUND: "Not Found",
  FETCHED_NURSINGHOMES: "Nursing Home Fetched Successfully",
  SUCCESS: "success",
  SETUP_PROFILE_MESSAGE: "Please setup the profile first.",
  TOKEN_VALID_MSG: "Token Is Valid.",
  TOKEN_INVALID_MSG: "Invalid Token.",
  PROFILE_FETCHED: "Profile fetched",
  PROFILE_FETCH_ERROR: "Error in profile fetching",
  SUBADMIT_FETCHED: "Subadmin Fetched Successfully.",
  COUNT_FETCHED: "Count Not fetched",
  COUNT_NOT_FETCHED: "Count For the users fetched.",
  NURSINGHOME_FETCHED: "Nursing Home Fetched Successfully.",
  USER_FECHED_MSG: "Users Fetched successfully",
  PASSWORD_CHANGED:"Password Change Succesfully",
  PASSWORD_FAILED_MSG:"Password Change Failed",
  USER_NOT_ACCESS_MSG:"Email does not exist",
  FORGET_PASSWORD_MSG:"Please check your mail to reset password.",
  PASSWORD_CHANGE_FAILED:"Forgot Password Failed.",
  PASSWORD_UPDATE_ERROR:"Error in password update",
  GROUP_CREATED:"Group Created Successfully",
  REQUIRED_MSG:"Please Fill all the feilds",
  MEMBER_MSG:"More than 2 users are required to form a group chat",
  REMOVED_MSG:"Removed Successfully",
  CHAT_NOT_FOUND:"Chat Not found",
  INVALID_DATA_MSG:"Invalid data passed into the request",
  CHAT_FETCHED_MSG:"Chat Fetched Successfully",
  INACTIVE_MSG:"User is not active, ask admin to activate the user",
  CHAT_ID_MSG:"Chat does not exist",
  ID_MSG:"User ID is not available in the given room"


  

}
